#! /usr/bin/env bash
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A qda -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A qda -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A qda -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A qda -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A qda -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A qda -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A qda -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A qda -S No
