#! /usr/bin/env bash
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A dtree -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A dtree -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A dtree -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A dtree -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A dtree -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A dtree -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A dtree -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A dtree -S No
