#! /usr/bin/env bash
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 0 -A knn -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 1 -A knn -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 2 -A knn -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 3 -A knn -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 4 -A knn -S No
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A knn -S Z
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A knn -S MinMax
python3 -u ../ml.py --datadir ../data/CSV/ --resultdir ../results/ -D 5 -A knn -S No
